version: '3.8'

services:
  app:
    container_name: backend-producto3
    build: .
    ports:
      - "4000:4000"
    environment:
      # lee estas variables desde tu archivo .env
      - MONGO_URI=${MONGO_URI}
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - app-network

networks:
  app-network: